name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Log in to DockerHub
        run: echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.USERNAME }}/node-cicd-app .

      - name: Push Docker Image
        run: docker push ${{ secrets.USERNAME }}/node-cicd-app
